services:
  postgres:
    container_name: analytics-service-db
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: analytics
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
    ports:
      - '5431:5432'