# .github/workflows/review-service.yml
name: Review Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'review-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'review-service/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make Gradlew Executable
        run: chmod +x ./review-service/gradlew

      - name: Build with Gradle
        working-directory: ./review-service
        run: ./gradlew build

      - name: Run tests
        working-directory: ./review-service
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inventory-test-results
          path: review-service/build/reports/tests/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: review-service-package
          path: review-service/build/libs/*.jar